version: "3.8"

services:
    MinecraftJava:
        image: itzg/minecraft-server
        container_name: "MinecraftJava_${NAME}"
        volumes:
            - $MC_JAVA_DIR/data:/data
        ports:
            - "25565:25565"
        tty: true
        stdin_open: true
        environment:
            - EULA=TRUE
            - MEMORY=$SERVER_MEMORY
            - ENABLE_ROLLING_LOGS=TRUE
            - VERSION=$MINECRAFT_VERION
            - OVERRIDE_SERVER_PROPERTIES=FALSE
            - SKIP_SERVER_PROPERTIES=TRUE
            - TZ=Europe/Berlin
        restart: unless-stopped

    MinecraftStats:
        image: chrisbesch/minecraft_stats
        container_name: "MinecraftStats_${NAME}"
        environment:
            - TZ=Europe/Berlin
            # configures the DockerCron container to send a SIGHUP to this container every five minutes
            - "CRON_TIME=*/5 * * * *"
        volumes:
            - $MC_JAVA_DIR/data/:/app/serverfiles:ro
            - ./config.json:/app/config.json:ro
            - $MC_JAVA_DIR/web:/app/www
        restart: unless-stopped

    MinecraftWeb:
        image: nginx
        container_name: "MinecraftWeb_${NAME}"
        volumes:
            - $MC_JAVA_DIR/web:/usr/share/nginx/html:ro
        environment:
            - LETSENCRYPT_HOST=${DOMAIN}
            - VIRTUAL_HOST=${DOMAIN}
        restart: unless-stopped
        networks: ["net"]

    MinecraftJavaBorgBackup:
        image: chrisbesch/docker_borg_backup
        volumes:
            - "$MC_JAVA_DIR:/origin:ro"
            - "$BORG_REPO:/repo"
            # needs to be able to start and stop other containers
            - "/var/run/docker.sock:/var/run/docker.sock:rw"
        environment:
            - TZ=Europe/Berlin
            - CRON_TIME=${BACKUP_CRON}
            - BORG_COMPRESSION
            - BORG_PREFIX=$NAME
            - PRUNE_CFG
            # stop these containers before backup
            - "CONTAINERS=MinecraftJava_${NAME} MinecraftStats_${NAME} MinecraftWeb_${NAME}"
        restart: "unless-stopped"

networks:
    net:
        external: true
