---

- name: Systemd Daemon Reload
  listen: mount
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Mount
  listen: mount
  become: true
  ansible.builtin.command: "mount -a"
  changed_when: true
