version: 4
mqtt:
    base_topic: zigbee2mqtt
    # set this to the correct address of the mqtt broker
    server: mqtt://192.168.188.50
serial:
    port: /dev/ttyACM0
    adapter: zstack
advanced:
    channel: 15
    network_key: GENERATE
    pan_id: GENERATE
    ext_pan_id: GENERATE
frontend:
    enabled: true
homeassistant:
    enabled: false
