---

# - name: Docker Compose Down
#   listen: restart_docker_compose
#   community.docker.docker_compose_v2:
#     docker_host: "{{ docker_host }}"
#     project_src: "{{ docker_compose_dir }}"
#     remove_orphans: true
#     remove_volumes: true
#     state: absent

- name: Docker Compose Pull and Up
  listen: restart_docker_compose
  community.docker.docker_compose_v2:
    docker_host: "{{ docker_host }}"
    project_src: "{{ docker_cron_dir }}"
    pull: always
    recreate: always
    remove_orphans: true
    state: present
