---

- name: Create Docker chore_planner Directory
  ansible.builtin.file:
    dest: "{{ docker_chore_planner_dir }}"
    state: directory
    mode: "0755"
  notify: docker_chore_planner_restart

- name: Create Docker chore_planner Borg Directory
  ansible.builtin.file:
    dest: "{{ docker_chore_planner_borg_dir }}"
    state: directory
    mode: "0755"
  notify: docker_chore_planner_restart

- name: Template docker-compose.yml
  ansible.builtin.template:
    src: "docker-compose.yml.j2"
    dest: "{{ docker_chore_planner_dir }}/docker-compose.yml"
    mode: "0644"
  notify: docker_chore_planner_restart

- name: Force Pull
  ansible.builtin.command: "true"
  changed_when: force_pull
  notify: docker_chore_planner_restart

- name: Force Stop Container
  ansible.builtin.command: "true"
  changed_when: stop_container
  notify: docker_chore_planner_down
