# Run this after the server has been prepared (i.e. the freeman user has been created).
---

- name: Setup Users
  hosts: all
  remote_user: freeman
  roles:
    - role: setup_users

- name: Install Packages
  hosts: all
  remote_user: freeman
  roles:
    - role: install_packages

- name: Create Swapfile
  hosts: hetzner
  remote_user: freeman
  roles:
    - role: swap
      tags: swap

- name: Mount Box
  hosts: hetzner
  remote_user: freeman
  roles:
    - role: box_mount
      tags: box
