# Run this after the server has been prepared (i.e. the freeman user has been created).
---

- hosts: all
  remote_user: freeman
  roles:
    - role: setup_users

- hosts: all
  remote_user: freeman
  roles:
    - role: install_packages
