# This installs and starts/restarts all Docker applications.
---

- name: Install Docker Apps
  hosts: all
  remote_user: apprun
  vars:
    force_pull: false
    stop_container: false
  roles:
    - role: docker_cron
      tags: cron
    - role: docker_nginx
      tags: nginx
    - role: docker_tandoor
      tags: tandoor
    - role: docker_firefly
      tags: firefly
    - role: docker_minecraft
      tags: minecraft
