# Run this after the server has been created and Debian has been installed.
---

- name: Hetzner Prepare as Root
  hosts: hetzner
  remote_user: root
  roles:
    - role: prepare_as_root

- name: Raspberry Prepare as Root
  hosts: raspberry
  remote_user: pi
  become: true
  roles:
    - role: prepare_as_root
