# This installs and starts all Docker applications.
---

- name: Install Docker Apps
  hosts: all
  remote_user: apprun
  vars:
    force_pull: true
    stop_container: false
  roles:
    - role: docker_cron
      tags: cron
    - role: docker_nginx
      tags: nginx
    - role: docker_tandoor
      tags: tandoor
    - role: docker_firefly
      tags: firefly
