# This installs and starts/restarts all Docker applications.
---

- name: Install Docker Apps
  hosts: all
  remote_user: apprun
  vars:
    force_pull: false
    stop_container: true
  roles:
    - role: docker_cron
