# Run this when all containers have been shut down.
---

- name: Update Packages
  hosts: all
  remote_user: freeman
  roles:
    - role: update_packages

- name: Set freeman Shell Configs
  hosts: all
  remote_user: freeman
  roles:
    - role: shell_configs

- name: Set apprun Shell Configs
  hosts: all
  remote_user: apprun
  roles:
    - role: shell_configs
