---

- name: Create Docker Photo Directory
  ansible.builtin.file:
    dest: "{{ docker_photo_dir }}"
    state: directory
    mode: "0755"
  notify: docker_photo_restart

- name: Create Docker Photo Borg Directory
  ansible.builtin.file:
    dest: "{{ docker_photo_borg_dir }}"
    state: directory
    mode: "0755"
  notify: docker_photo_restart

- name: Create Docker Photo Originals Directory
  ansible.builtin.file:
    dest: "{{ docker_photo_originals_dir }}"
    state: directory
    mode: "0755"
  notify: docker_photo_restart

- name: Template docker-compose.yml
  ansible.builtin.template:
    src: "docker-compose.yml.j2"
    dest: "{{ docker_photo_dir }}/docker-compose.yml"
    mode: "0644"
  notify: docker_photo_restart

- name: Force Pull
  ansible.builtin.command: "true"
  changed_when: force_pull
  notify: docker_photo_restart

- name: Force Stop Container
  ansible.builtin.command: "true"
  changed_when: stop_container
  notify: docker_photo_down
