---

- name: Create Docker SSH Jump Directory
  ansible.builtin.file:
    dest: "{{ docker_ssh_jump_dir }}"
    state: directory
    mode: "0755"
  notify: docker_ssh_jump_restart

- name: Copy authorized_keys
  ansible.builtin.copy:
    src: "authorized_keys"
    dest: "{{ docker_ssh_jump_dir }}/authorized_keys"
    mode: "0600"
  notify: docker_ssh_jump_restart

- name: Copy entrypoint.sh
  ansible.builtin.copy:
    src: "entrypoint.sh"
    dest: "{{ docker_ssh_jump_dir }}/entrypoint.sh"
    mode: "0755"
  notify: docker_ssh_jump_restart

- name: Template docker-compose.yml
  ansible.builtin.template:
    src: "docker-compose.yml.j2"
    dest: "{{ docker_ssh_jump_dir }}/docker-compose.yml"
    mode: "0644"
  notify: docker_ssh_jump_restart

- name: Force Pull
  ansible.builtin.command: "true"
  changed_when: force_pull
  notify: docker_ssh_jump_restart

- name: Force Stop Container
  ansible.builtin.command: "true"
  changed_when: stop_container
  notify: docker_ssh_jump_down
