# based on https://linuxhandbook.com/install-nextcloud-docker
version: "3.7"

services:
    NCFrontend:
        # https://hub.docker.com/_/nextcloud
        image: "nextcloud:25.0.12"
        container_name: "NCFrontend_${NAME}"

        volumes:
            - "${NC_PATH}/nc_data:/var/www/html"
            - "${NC_LFS_PATH}:/lfs"

        environment:
            - LETSENCRYPT_HOST=${DOMAIN}
            - VIRTUAL_HOST=${DOMAIN}
            - TRUSTED_PROXIES
            - OVERWRITEPROTOCOL
            - MYSQL_DATABASE=NC
            - MYSQL_USER=nextcloud
            - MYSQL_PASSWORD
            - MYSQL_HOST=NCDatabase
            - NEXTCLOUD_TRUSTED_DOMAINS=${DOMAIN}
            - TZ=Europe/Berlin

        depends_on:
            - "NCDatabase"
        # accept docker stop
        restart: "unless-stopped"
        networks: ["net", "common"]

    NCDatabase:
        # https://hub.docker.com/_/mariadb
        # https://docs.nextcloud.com/server/latest/admin_manual/installation/system_requirements.html
        image: "mariadb:10.11.5"
        container_name: "NCDatabase_${NAME}"

        volumes:
            - "${NC_PATH}/nc_maria_db:/var/lib/mysql"

        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=1
            # - MYSQL_ROOT_PASSWORD
            - MYSQL_DATABASE=NC
            - MYSQL_USER=nextcloud
            - MYSQL_PASSWORD
            - MARIADB_AUTO_UPGRADE=true
            - TZ=Europe/Berlin

        # accept docker stop
        restart: "unless-stopped"
        networks: ["common"]

    DockerBorgBackup:
        image: chrisbesch/docker_borg_backup
        volumes:
            - "$NC_PATH:/origin:ro"
            - "$BORG_REPO:/repo"
            # exclude the music dir
            - "./borg_exclude:/borg_exclude"
            # needs to be able to start and stop other containers
            - "/var/run/docker.sock:/var/run/docker.sock:rw"
        environment:
            - TZ=Europe/Berlin
            - CRON_TIME=${BACKUP_CRON}
            - BORG_COMPRESSION
            - BORG_PREFIX=$NAME
            - PRUNE_CFG
            # stop these containers before backup
            - "CONTAINERS=NCDatabase_${NAME} NCFrontend_${NAME}"

    # enable cron for background job in administrative basic settings
    NCCron:
        image: alpine
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:rw"
        command: sh -c 'apk update && apk add docker-cli && sh -c "echo \"${NEXTCLOUD_CRON} docker exec -u www-data NCFrontend_${NAME} php -f /var/www/html/cron.php\" | crontab - && crond -f -L /dev/stdout"'
        restart: "unless-stopped"

networks:
    net:
        external: true
    common:
        internal: true

