services:
    UptimeKuma:
        # https://hub.docker.com/r/louislam/uptime-kuma/tags
        image: louislam/uptime-kuma:1.23.11
        container_name: uptime-kuma
        volumes:
            - "${UPKU_PATH}:/app/data"
        restart: unless-stopped
        environment:
            DOMAIN: ${DOMAIN}
            VIRTUAL_HOST: ${DOMAIN}
            VIRTUAL_PORT: 3001
            TZ: Europe/Berlin
        networks: ["net"]
        logging:
            driver: "local"
            options:
                max-size: "10m"
                max-file: "3"

networks:
    net:
        external: true

