# based on https://linuxhandbook.com/install-nextcloud-docker
version: "3.7"

services:

    NCDatabase:
        image: "mariadb:10.7.4"
        
        volumes:
          - "${NC_PATH}/nc_maria_db:/var/lib/mysql"

        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=1
            # - MYSQL_ROOT_PASSWORD
            - MYSQL_DATABASE=NC
            - MYSQL_USER=nextcloud
            - MYSQL_PASSWORD

        restart: "always"
        networks: ["common"]

    NCFrontend:
        image: "nextcloud:24.0.3"

        volumes: 
          - "${NC_PATH}/nc_data:/var/www/html"

        environment:
            - LETSENCRYPT_HOST=${DOMAIN}
            - VIRTUAL_HOST=${DOMAIN}
            - TRUSTED_PROXIES
            - OVERWRITEPROTOCOL
            - MYSQL_DATABASE=NC
            - MYSQL_USER=nextcloud
            - MYSQL_PASSWORD
            - MYSQL_HOST=NCDatabase
            - NEXTCLOUD_TRUSTED_DOMAINS=${DOMAIN}

        depends_on:
            - "NCDatabase"
        restart: "always"
        networks: ["net", "common"]

networks:
    net:
        external: true
    common:
        internal: true

