# based on https://linuxhandbook.com/install-nextcloud-docker
version: "3.7"

services:

    NCDatabase:
        image: "mariadb:10.9.2"
        container_name: "NCDatabase_${NAME}"

        volumes:
          - "${NC_PATH}/nc_maria_db:/var/lib/mysql"

        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=1
            # - MYSQL_ROOT_PASSWORD
            - MYSQL_DATABASE=NC
            - MYSQL_USER=nextcloud
            - MYSQL_PASSWORD
            - MARIADB_AUTO_UPGRADE=true

        # accept docker stop
        restart: "unless-stopped"
        networks: ["common"]

    NCFrontend:
        image: "nextcloud:24.0.4"
        container_name: "NCFrontend_${NAME}"

        volumes:
          - "${NC_PATH}/nc_data:/var/www/html"

        environment:
            - LETSENCRYPT_HOST=${DOMAIN}
            - VIRTUAL_HOST=${DOMAIN}
            - TRUSTED_PROXIES
            - OVERWRITEPROTOCOL
            - MYSQL_DATABASE=NC
            - MYSQL_USER=nextcloud
            - MYSQL_PASSWORD
            - MYSQL_HOST=NCDatabase
            - NEXTCLOUD_TRUSTED_DOMAINS=${DOMAIN}

        depends_on:
            - "NCDatabase"
        # accept docker stop
        restart: "unless-stopped"
        networks: ["net", "common"]

    DockerBorgBackup:
        image: chrisbesch/docker_borg_backup
        volumes:
            - "$NC_PATH:/origin:ro"
            - "$BORG_REPO:/repo"
            # needs to be able to start and stop other containers
            - "/var/run/docker.sock:/var/run/docker.sock:rw"
        environment:
            - TZ=Europe/Berlin
            - CRON_TIME=${BACKUP_CRON}
            - BORG_COMPRESSION
            - BORG_PREFIX=$NAME
            - PRUNE_CFG
            # stop these containers before backup
            - "CONTAINERS=NCDatabase_${NAME} NCFrontend_${NAME}"

    DockerCron:
        image: chrisbesch/docker_cron
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:rw"
        environment:
            - TZ=Europe/Berlin

networks:
    net:
        external: true
    common:
        internal: true

