# After the server has been created, this is the first role to run.
# It is the only role that is not idempotent (i.e. you won't be able to run it twice).
# It uses the root user the server starts with, which will be disabled later on.
#
# This role contains only what is absolutely necessary.
#
# The reboot is needed because of the pi user needs to be logged out completely before deleting it.
---

- name: Create admin group
  ansible.builtin.group:
    name: admin
    gid: 2845
  notify: restart

- name: Create freeman
  ansible.builtin.user:
    name: freeman
    uid: 2845
    group: admin
    groups: sudo
    password_lock: true
    shell: /bin/bash
  notify: restart

- name: Setup sudo
  community.general.sudoers:
    name: sudo_group_rule
    commands: ALL
    group: sudo
    nopassword: true
  notify: restart

- name: Add SSH authorized key for freeman
  ansible.posix.authorized_key:
    user: freeman
    key: "{{ lookup('file', '{{ ssh_pub_key_path }}') }}"
  notify: restart
