---

- name: Create Docker Jelly Directory
  ansible.builtin.file:
    dest: "{{ docker_jelly_dir }}"
    state: directory
    mode: "0755"
  notify: docker_jelly_restart

- name: Copy config.json
  ansible.builtin.copy:
    src: "config.json"
    dest: "{{ docker_jelly_dir }}/config.json"
    mode: "0644"
  notify: docker_jelly_restart

- name: Template docker-compose.yml
  ansible.builtin.template:
    src: "docker-compose.yml.j2"
    dest: "{{ docker_jelly_dir }}/docker-compose.yml"
    mode: "0644"
  notify: docker_jelly_restart

- name: Force Pull
  ansible.builtin.command: "true"
  changed_when: force_pull
  notify: docker_jelly_restart

- name: Force Stop Container
  ansible.builtin.command: "true"
  changed_when: stop_container
  notify: docker_jelly_down
