version: "3.9"

services:

    GitBackup:
        image: "chrisbesch/docker_git_backup"

        volumes:
            - "${BACKUP_REPO}:/var/lib/git_backup/repo"
            - "${BACKUP_TEMP}:/var/lib/git_backup/temp"
            - "./other_repos.conf:/var/lib/git_backup/other_repos.conf:ro"
        
        environment:
            - GITHUB_USERNAME
            - GITHUB_PASSWORD
            - BORG_COMPRESSION
            - PRUNE_CFG
            - CRON_TIME
            - TZ=Europe/Berlin

        restart: "always"
