version: "3.9"

services:

    git_backup:
        image: "chrisbesch/git_backup"

        volumes:
            - "${BACKUP_REPO}:/var/lib/git_backup/repo"
            - "${BACKUP_TEMP}:/var/lib/git_backup/temp"
            - "${BACKUP_CONFIGS}:/var/lib/git_backup/configs:ro"
        
        environment:
            - GITHUB_USERNAME
            - GITHUB_PASSWORD
            - CRON_TIME

        restart: "always"

    docker_cron:
        image: "chrisbesch/docker_cron"

        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:rw"
        environment:
            - TZ=Europe/Berlin

        restart: "always"

