version: "3.7"

services:
    BorgServer:
        image: chrisbesch/docker_borg_server
        volumes:
            - "./authorized_keys:/var/lib/borg_server/authorized_keys:ro"
            # all repos shall be mounted into subdirs of /var/lib/borg_server/repos
            - "$NC_REPO:/var/lib/borg_server/repos/nextcloud_backup"
            - "$TD_REPO:/var/lib/borg_server/repos/tandoor_backup"
            - "$MC_JAVA_REPO:/var/lib/borg_server/repos/minecraft_backup"
            - "$FF_REPO:/var/lib/borg_server/repos/firefly_backup"
            - "$GIT_REPO:/var/lib/borg_server/repos/git_backup"
            - "$MUSIC_REPO:/var/lib/borg_server/repos/music"
        ports:
            - "$PORT:22"
        environment:
            - TZ=Europe/Berlin
        restart: "always"

