---

STAGING:
  vars:
    ssh_pub_key_path: /home/chris/.ssh/chris.pub

    apprun_dir: "/home/apprun"

    box_dir: "{{ apprun_dir }}/box"
    docker_jelly_media_dir: "{{ box_dir }}/jelly_media"
    docker_nextcloud_lfs_dir: "{{ box_dir }}/nextcloud_lfs"
    docker_photo_originals_dir: "{{ box_dir }}/images"

    borg_dir: "{{ box_dir }}/borg"
    docker_firefly_borg_dir: "{{ borg_dir }}/firefly"
    docker_minecraft_borg_dir: "{{ borg_dir }}/minecraft"
    docker_nextcloud_borg_dir: "{{ borg_dir }}/nextcloud"
    docker_photo_borg_dir: "{{ borg_dir }}/photo"
    docker_tandoor_borg_dir: "{{ borg_dir }}/tandoor"
    docker_chore_planner_borg_dir: "{{ borg_dir }}/chore_planner"

    app_dir: "{{ apprun_dir }}/app"
    docker_cron_dir: "{{ app_dir }}/cron"
    docker_firefly_dir: "{{ app_dir }}/firefly"
    docker_jelly_dir: "{{ app_dir }}/jelly"
    docker_minecraft_dir: "{{ app_dir }}/minecraft"
    docker_nextcloud_dir: "{{ app_dir }}/nextcloud"
    docker_nginx_dir: "{{ app_dir }}/nginx"
    docker_photo_dir: "{{ app_dir }}/photo"
    docker_tandoor_dir: "{{ app_dir }}/tandoor"
    docker_chore_planner_dir: "{{ app_dir }}/chore_planner"

    domain: staging.chris-besch.com
    docker_firefly_domain: "firefly.{{ domain }}"
    docker_jelly_domain: "jelly.{{ domain }}"
    docker_minecraft_web_domain: "mc.{{ domain }}"
    docker_nextcloud_domain: "nextcloud.{{ domain }}"
    docker_photo_domain: "photo.{{ domain }}"
    docker_tandoor_domain: "recipe.{{ domain }}"

    docker_socket: "/var/run/docker.sock"
    docker_host: "unix://{{ docker_socket }}"
    # this is also used as the trusted proxies for firefly and nextcloud
    docker_net_subnet: 172.20.0.0/16

    borg_prune_cfg: "--keep-last 1 --keep-daily 4 --keep-monthly 3 --keep-yearly 1"
  hosts:
    amd64hetzner08:
      ansible_host: 167.235.241.205
